# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Programando na Madrugada
description: >- # this means to ignore newlines until "baseurl:"
  Programação na melhor hora do dia
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.luizpicanco.com" # the base hostname & protocol for your site, e.g. http://example.com
author: 
  name: "Luiz Picanço"
  email: lpicanco@gmail.com
twitter_username: lpicanco
github_username:  lpicanco

paginate: 10 # amount of posts to show
paginate_path: /page:num/

breadcrumbs: false

# Build settings
theme: minimal-mistakes-jekyll
# minimal_mistakes_skin: "air"
plugins:
  - jekyll-feed
  - jekyll-archives

cayman-blog:
  date_format: "%b %-d, %Y"

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: posts
    values:
      read_time: true  

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
